#!/bin/bash

mkdir -p output

pandoc markdown/resume.md -o index.html -t html5 \
  -smart \
  --standalone \
  --email-obfuscation=references \
  --data-dir=_pandoc \
  --include-in-header=_pandoc/header_styles.html \
  --include-before-body=_pandoc/header.html \
  --include-after-body=_pandoc/footer.html \
  --variable="pagetitle:Resume :: Matt Valerio"

pandoc markdown/resume.md -o output/resume.odt --reference-doc=_pandoc/reference.odt

libreoffice --headless --convert-to doc --outdir output output/resume.odt
libreoffice --headless --convert-to pdf --outdir output output/resume.odt